language: php

php:
  - 7.3
  - 7.4
  - 8.0

install:
  - composer install

script:
  - mkdir -p logs
  - phpunit --configuration .phpunit.travis.xml tests

after_script:
  - php vendor/bin/php-coveralls -v